/*
 * scaling.js -- what depth actually buys, plotted.
 *
 * Accuracy against mask count, on a log x-axis because the range is 2 to 80.
 * Two series, deliberately kept apart by colour, because mixing them is the
 * single easiest way to lie with this data:
 *
 *   ranking protocol   20k images x 12 epochs. Cheap, used to rank geometries
 *                      against each other. Its accuracies are depressed by the
 *                      short budget and must NEVER be read against the headline.
 *   full budget        60k images. Two runs only: the 5-mask design at 0.7990
 *                      and the 56-mask one at 0.9040. These two are
 *                      the same measurement as each other and as every number
 *                      quoted elsewhere on the site.
 *
 * At each depth the ranking series takes the run closest to the iso-reach target,
 * so every point spends the same total diffractive reach and only the number of
 * masks changes. Data is window.OPTICS_SWEEP (optics_sweep.js, generated by
 * apps/sweep_report.py); nothing here is typed in.
 *
 * Usage:  window.PhotonnScaling.mount(el)
 */
(function () {
  "use strict";

  const STYLE_ID = "sc-style";
  const MAX_DPR = 2;
  const D = (typeof window !== "undefined" && window.OPTICS_SWEEP)
    ? window.OPTICS_SWEEP
    : (typeof require !== "undefined" ? require("./optics_sweep.js") : null);

  const CSS = `
.sc-root{--sc-fg:#1b1f24;--sc-muted:#5a6472;--sc-panel:#f4f6f9;--sc-border:#d7dde5;
  --sc-rank:#6a7f99;--sc-full:#c9701f;
  color:var(--sc-fg);font:13px/1.45 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;
  background:var(--sc-panel);border:1px solid var(--sc-border);border-radius:10px;padding:13px 15px;}
@media (prefers-color-scheme:dark){.sc-root{--sc-fg:#e6eaf0;--sc-muted:#9aa6b5;
  --sc-panel:#1c2128;--sc-border:#30363d;--sc-rank:#8fa6c2;--sc-full:#f2994a;}}
:root[data-theme="dark"] .sc-root{--sc-fg:#e6eaf0;--sc-muted:#9aa6b5;--sc-panel:#1c2128;
  --sc-border:#30363d;--sc-rank:#8fa6c2;--sc-full:#f2994a;}
:root[data-theme="light"] .sc-root{--sc-fg:#1b1f24;--sc-muted:#5a6472;--sc-panel:#f4f6f9;
  --sc-border:#d7dde5;--sc-rank:#6a7f99;--sc-full:#c9701f;}
.sc-root canvas{width:100%;height:auto;display:block;}
.sc-key{display:flex;gap:18px;flex-wrap:wrap;font-size:12px;color:var(--sc-muted);margin-top:9px;}
.sc-key i{display:inline-block;width:11px;height:11px;border-radius:3px;margin-right:6px;
  vertical-align:-1px;}
.sc-key .k-rank i{background:var(--sc-rank);}
.sc-key .k-full i{background:var(--sc-full);}
.sc-note{font-size:12px;color:var(--sc-muted);margin:9px 0 0;line-height:1.5;}
.sc-note b{color:var(--sc-fg);}
`;

  function injectStyle() {
    if (document.getElementById(STYLE_ID)) return;
    const s = document.createElement("style");
    s.id = STYLE_ID;
    s.textContent = CSS;
    document.head.appendChild(s);
  }

  function el(tag, cls, html) {
    const e = document.createElement(tag);
    if (cls) e.className = cls;
    if (html != null) e.innerHTML = html;
    return e;
  }

  /** One run per depth: the one spending closest to the iso-reach budget. */
  function depthSeries() {
    const target = D.iso_reach_px;
    const best = new Map();
    for (const p of D.scaling) {
      const prev = best.get(p.layers);
      if (!prev || Math.abs(p.reach_total - target) < Math.abs(prev.reach_total - target)) {
        best.set(p.layers, p);
      }
    }
    return [...best.values()].sort((a, b) => a.layers - b.layers);
  }

  function mount(container) {
    if (!D || !D.scaling) throw new Error("scaling.js: OPTICS_SWEEP.scaling missing.");
    injectStyle();
    const root = el("div", "sc-root");
    container.innerHTML = "";
    container.appendChild(root);

    const canvas = el("canvas");
    root.appendChild(canvas);
    root.appendChild(el("div", "sc-key",
      '<span class="k-rank"><i></i>ranking protocol &middot; ' + D.protocol.n_train / 1000
      + "k images, " + D.protocol.epochs + " epochs</span>"
      + '<span class="k-full"><i></i>full budget &middot; 60k images</span>'));
    const note = el("p", "sc-note");
    root.appendChild(note);

    const rank = depthSeries();
    const full = D.full;

    function draw() {
      const cssW = Math.max(280, root.clientWidth - 32);
      const cssH = Math.round(Math.min(300, Math.max(200, cssW * 0.52)));
      const dpr = Math.min(window.devicePixelRatio || 1, MAX_DPR);
      canvas.width = Math.round(cssW * dpr);
      canvas.height = Math.round(cssH * dpr);
      canvas.style.height = cssH + "px";
      const ctx = canvas.getContext("2d");
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
      ctx.clearRect(0, 0, cssW, cssH);

      const cs = getComputedStyle(root);
      const col = (n, f) => (cs.getPropertyValue(n).trim() || f);
      const fg = col("--sc-fg", "#1b1f24"), muted = col("--sc-muted", "#5a6472");
      const border = col("--sc-border", "#d7dde5");
      const cRank = col("--sc-rank", "#6a7f99"), cFull = col("--sc-full", "#c9701f");

      const padL = 46, padR = 14, padT = 12, padB = 34;
      const W = cssW - padL - padR, H = cssH - padT - padB;
      const yLo = 0.45, yHi = 0.95;
      const xLo = Math.log(2), xHi = Math.log(88);
      const X = (n) => padL + (Math.log(n) - xLo) / (xHi - xLo) * W;
      const Y = (a) => padT + (1 - (a - yLo) / (yHi - yLo)) * H;

      ctx.font = "11px ui-monospace, SFMono-Regular, Menlo, monospace";
      ctx.strokeStyle = border; ctx.fillStyle = muted; ctx.lineWidth = 1;
      for (let a = 0.5; a <= 0.9001; a += 0.1) {
        const y = Y(a);
        ctx.globalAlpha = 0.5;
        ctx.beginPath(); ctx.moveTo(padL, y); ctx.lineTo(padL + W, y); ctx.stroke();
        ctx.globalAlpha = 1;
        ctx.textAlign = "right"; ctx.textBaseline = "middle";
        ctx.fillText(a.toFixed(1), padL - 7, y);
      }
      ctx.textAlign = "center"; ctx.textBaseline = "top";
      for (const n of [2, 5, 10, 20, 40, 80]) {
        ctx.fillText(String(n), X(n), padT + H + 7);
      }
      ctx.fillText("masks", padL + W / 2, padT + H + 21);

      // ranking series
      ctx.strokeStyle = cRank; ctx.lineWidth = 2;
      ctx.beginPath();
      rank.forEach((p, i) => (i ? ctx.lineTo(X(p.layers), Y(p.acc)) : ctx.moveTo(X(p.layers), Y(p.acc))));
      ctx.stroke();
      ctx.fillStyle = cRank;
      for (const p of rank) {
        ctx.beginPath(); ctx.arc(X(p.layers), Y(p.acc), 3.4, 0, 2 * Math.PI); ctx.fill();
      }

      // full-budget points, joined by a dashed line to show the same jump
      ctx.strokeStyle = cFull; ctx.lineWidth = 2;
      ctx.setLineDash([5, 4]);
      ctx.beginPath();
      full.forEach((p, i) => (i ? ctx.lineTo(X(p.layers), Y(p.acc)) : ctx.moveTo(X(p.layers), Y(p.acc))));
      ctx.stroke();
      ctx.setLineDash([]);
      for (const p of full) {
        ctx.fillStyle = cFull;
        ctx.beginPath(); ctx.arc(X(p.layers), Y(p.acc), 5.2, 0, 2 * Math.PI); ctx.fill();
        ctx.fillStyle = fg;
        ctx.textAlign = p.layers < 10 ? "left" : "right";
        ctx.textBaseline = "bottom";
        ctx.fillText(p.acc.toFixed(4), X(p.layers) + (p.layers < 10 ? 9 : -9), Y(p.acc) - 5);
      }
      ctx.fillStyle = muted;
      ctx.textAlign = "left"; ctx.textBaseline = "top";
      ctx.fillText("accuracy", padL - 38, padT - 4);
    }

    const first = rank[0], last = rank[rank.length - 1];
    const gain = (full[1].acc - full[0].acc) * 100;
    note.innerHTML = "Both series climb and both <b>flatten</b>. Across the ranking runs, going "
      + "from " + first.layers + " masks to " + last.layers + " lifts accuracy from "
      + first.acc.toFixed(4) + " to " + last.acc.toFixed(4) + ", and the last doubling of depth "
      + "buys under half a point. The two full-budget runs are the ones to read against each "
      + "other and against the rest of this site: <b>eleven times the masks for "
      + gain.toFixed(1) + " points</b>.";

    draw();
    window.addEventListener("resize", draw);
    if (window.matchMedia) {
      const mq = window.matchMedia("(prefers-color-scheme:dark)");
      (mq.addEventListener ? mq.addEventListener.bind(mq, "change") : mq.addListener.bind(mq))(draw);
    }
    return { redraw: draw };
  }

  const API = { mount };
  if (typeof window !== "undefined") window.PhotonnScaling = API;
  if (typeof module !== "undefined" && module.exports) module.exports = API;
})();
