"""The free-space/chip correspondence figure must not drift from the models.

``apps/web/analogy.js`` and ``apps/analogy_figure.py`` both argue that the D2NN
and the MZI mesh are the same alternating machine differing only in reach per
layer, and both quote numbers for it. Those numbers are *derived*, never typed:
they live in the committed ``apps/web/analogy_geom.js``, generated by
``apps.export_analogy_web``. These tests re-derive them from the physics and the
model code so a stale or hand-edited bundle fails loudly.

Split by what a fresh clone can see: everything here runs from committed files
alone, except the last test, which needs ``exports/*.h5`` (gitignored) and skips
without them.
"""
from __future__ import annotations

import json
import os
import re

import numpy as np
import pytest

from photonn.detect import default_regions
from photonn.layers import MZIMeshLayer
from photonn.propagate import diffraction_reach_px

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
GEOM_JS = os.path.join(REPO, "apps", "web", "analogy_geom.js")
ANALOGY_JS = os.path.join(REPO, "apps", "web", "analogy.js")


@pytest.fixture(scope="module")
def geom():
    from apps.analogy_figure import load_geom
    assert os.path.exists(GEOM_JS), "run `python -m apps.export_analogy_web` first"
    return load_geom(GEOM_JS)


# ------------------------------------------------------------------- the physics
def test_reach_is_the_nyquist_ray_below_z_crit():
    """Reach per hop is z*lam/(2*dx^2) exactly, while the band limit is inactive."""
    n, dx, lam = 128, 8e-6, 532e-9
    z_crit = n * dx**2 / lam
    for z in (0.5e-3, 3.0e-3, 0.9 * z_crit):
        assert diffraction_reach_px(n, dx, lam, z) == pytest.approx(
            z * lam / (2 * dx**2), rel=1e-12)


def test_reach_saturates_once_the_band_limit_bites():
    """Past z_crit the Matsushima cut, not Nyquist, sets the reach -- so it must
    fall below the paraxial line rather than keep growing with z."""
    n, dx, lam = 128, 8e-6, 532e-9
    z_crit = n * dx**2 / lam
    paraxial = lambda z: z * lam / (2 * dx**2)
    assert diffraction_reach_px(n, dx, lam, 4 * z_crit) < paraxial(4 * z_crit)
    # Still monotonic in z: a longer hop never reaches less far.
    reaches = [diffraction_reach_px(n, dx, lam, k * z_crit) for k in (1, 2, 4, 8)]
    assert all(b >= a for a, b in zip(reaches, reaches[1:]))


def test_committed_reach_matches_the_propagator(geom):
    d = geom["d2nn"]
    hop = diffraction_reach_px(d["n"], d["dx"], d["wavelength"], d["separation"])
    assert d["reach_px_per_hop"] == pytest.approx(hop, rel=1e-12)
    assert d["hops"] == d["n_layers"] + 1
    assert d["reach_px_total"] == pytest.approx(d["hops"] * hop, rel=1e-12)
    assert d["z_crit_m"] == pytest.approx(d["n"] * d["dx"] ** 2 / d["wavelength"], rel=1e-12)
    # The figure only claims a clean z*lam/(2*dx^2) reach while that holds.
    assert d["separation"] < d["z_crit_m"]


# --------------------------------------------------------------- the connectivity
def test_committed_detector_layout_is_the_models_layout(geom):
    d = geom["d2nn"]
    expected = [[r.y0, r.y1, r.x0, r.x1] for r in default_regions(d["n"])]
    assert d["regions"] == expected
    assert d["detector_x"] == [min(r[2] for r in expected), max(r[3] - 1 for r in expected)]
    assert d["detector_y"] == [min(r[0] for r in expected), max(r[1] - 1 for r in expected)]


def test_committed_input_window_matches_the_encoder(geom):
    """The window must be the one photonn.train._embed actually writes into."""
    from photonn.train import embed_input
    d = geom["d2nn"]
    canvas = embed_input(np.ones((1, 28, 28), dtype="f4"), n=d["n"],
                         input_frac=d["input_frac"])[0].numpy()
    occupied = np.flatnonzero(canvas.any(axis=0))
    assert d["input_window"] == [int(occupied[0]), int(occupied[-1])]


def test_required_reach_is_the_worst_input_to_detector_pair(geom):
    """Per axis: an input pixel at one window edge must reach the farthest
    detector pixel. Reach is per-axis because the FFT band is a square in
    (fx, fy), so x and y are separate one-dimensional tests."""
    d = geom["d2nn"]
    w0, w1 = d["input_window"]
    for axis, need in (("detector_x", d["required_px_x"]), ("detector_y", d["required_px_y"])):
        lo, hi = d[axis]
        assert need == max(w1 - lo, hi - w0)
    assert d["required_px"] == max(d["required_px_x"], d["required_px_y"])
    assert d["margin_px"] == pytest.approx(d["reach_px_total"] - d["required_px"], rel=1e-12)


def test_the_design_is_connected_but_only_just(geom):
    """The finding the figure states: full connectivity, with ~1% of margin.

    If a retrained model moves the operating point this test is what tells you
    the claim on the page has to change too.
    """
    d = geom["d2nn"]
    assert d["margin_px"] > 0, "the stack can no longer link every pixel to every detector"
    assert d["margin_px"] / d["required_px"] < 0.05, "margin is no longer 'only just'"
    # Equivalently, as a tolerance on the one dimension a builder controls.
    z_min = d["required_px"] * 2 * d["dx"] ** 2 / (d["hops"] * d["wavelength"])
    assert d["min_separation_m"] == pytest.approx(z_min, rel=1e-12)
    assert d["min_separation_m"] < d["separation"]


# ------------------------------------------------------------------ the topology
def test_committed_mesh_is_the_clements_schedule(geom):
    """The drawn columns are MZIMeshLayer's own schedule, not a redrawn brick."""
    m = geom["mesh"]
    layer = MZIMeshLayer(m["n_modes"])
    assert m["columns"] == [[mode for mode, _ in pairs] for pairs in layer._schedule]
    assert m["n_columns"] == m["n_modes"] == 36
    assert m["n_mzi"] == layer.n_mzi == m["n_modes"] * (m["n_modes"] - 1) // 2 == 630
    assert sorted({len(c) for c in m["columns"]}) == [17, 18]
    # U . Sigma . V+ puts two of these meshes in series.
    assert (m["svd_columns"], m["svd_mzi"]) == (2 * m["n_columns"], 2 * m["n_mzi"])


def test_mesh_reach_is_one_mode_and_the_bound_is_tight(geom):
    """One coupler column mixes one neighbour, so n-1 columns link the worst pair
    -- and Clements supplies exactly n. That is the contrast with the D2NN."""
    m = geom["mesh"]
    assert m["reach_modes_per_column"] == 1
    assert m["required_columns"] == m["n_modes"] - 1
    assert m["n_columns"] >= m["required_columns"]


# ------------------------------------------------- the widget reads what exists
def test_widget_only_reads_fields_the_bundle_defines(geom):
    """Guard the JS/Python contract: a renamed key must not fail silently in the
    browser, where a missing field renders as 'undefined' rather than raising."""
    source = open(ANALOGY_JS, encoding="utf-8").read()
    for var, section in (("D", "d2nn"), ("M", "mesh")):
        used = set(re.findall(r"\b%s\.([A-Za-z_]\w*)" % var, source))
        missing = used - set(geom[section])
        assert not missing, f"analogy.js reads {var}.{sorted(missing)}, absent from {section}"


def test_bundle_declares_its_schema(geom):
    from apps.export_analogy_web import SCHEMA
    assert geom["schema"] == SCHEMA


# ------------------------------------------ regeneration check (needs the exports)
@pytest.mark.skipif(
    not os.path.exists(os.path.join(REPO, "exports", "d2nn_phase2.h5")),
    reason="exports/*.h5 are gitignored; run apps.train_d2nn / apps.train_mesh to regenerate",
)
def test_committed_bundle_is_up_to_date_with_the_handoffs(geom, tmp_path):
    """With the exports present, the committed file must be what the exporter
    would write now -- otherwise the page is quoting a superseded model."""
    from apps.export_analogy_web import write_geom_js
    from apps.analogy_figure import load_geom

    fresh = load_geom(write_geom_js(str(tmp_path / "analogy_geom.js")))
    assert json.dumps(fresh, sort_keys=True) == json.dumps(geom, sort_keys=True), (
        "apps/web/analogy_geom.js is stale -- re-run `python -m apps.export_analogy_web`"
    )
