"""The exporters are entered, not merely imported.

Every widget bundle in ``apps/web`` is generated by one of these functions, and
each one reads the handoff. The bundles are committed, so the tests that check
them read the *committed* file and never call the code that wrote it -- which
means an exporter can be broken outright and the suite stays green. That is not
hypothetical: a missing import inside ``mesh_weights`` raised ``NameError`` on
the first line of its body and 373 tests passed over it, because nothing in the
suite had called it since.

These are smoke tests, deliberately shallow: they enter each reader and assert
the one number that proves it got all the way through. What the bundles *say* is
already pinned by ``test_web_contract.py`` and ``test_correspondence.py``.

Skipped when ``exports/`` is empty -- it is gitignored, and re-training to run a
smoke test is not a trade worth making.
"""
import os

import pytest

HERE = os.path.dirname(os.path.abspath(__file__))
EXPORTS = os.path.join(os.path.dirname(HERE), "exports")

D2NN_H5 = os.path.join(EXPORTS, "d2nn_phase2.h5")
MESH_H5 = os.path.join(EXPORTS, "mesh_phase3.h5")
DEEP_H5 = os.path.join(EXPORTS, "deep_mesh_phase5.h5")


def need(path):
    if not os.path.exists(path):
        pytest.skip(f"{os.path.basename(path)} not exported; exports/ is gitignored")


def test_mesh_weights_reads_the_handoff():
    need(MESH_H5)
    from apps.export_mesh_web import mesh_weights

    assert 0.0 < mesh_weights()["accuracy"] <= 1.0


def test_d2nn_geometry_reads_the_handoff():
    need(D2NN_H5)
    from apps.export_analogy_web import d2nn_geometry

    geom = d2nn_geometry()
    assert 0.0 < geom["accuracy"] <= 1.0
    assert geom["required_px"] > 0


def test_mesh_geometry_reads_the_handoff():
    need(MESH_H5)
    from apps.export_analogy_web import mesh_geometry

    assert 0.0 < mesh_geometry()["accuracy"] <= 1.0


def test_load_handoff_reads_the_masks():
    need(D2NN_H5)
    from apps.export_d2nn_web import load_handoff

    hand = load_handoff()
    assert hand["masks"].shape == (hand["n_layers"], hand["n"], hand["n"])


def test_deep_mesh_web_reads_the_handoff():
    need(DEEP_H5)
    from apps.export_deep_mesh_web import build

    payload, reference = build()
    assert 0.0 < payload["provenance"]["accuracy"] <= 1.0
    assert len(reference["logits"]) == len(payload["gallery_labels"])
