function p = deep_params(handoff)
%DEEP_PARAMS The ideal, unperturbed parameter set of a deep_mesh handoff.
%   P = MESHMODEL.DEEP_PARAMS(HANDOFF) returns the struct meshmodel.evaluate_deep
%   consumes and the +err sources perturb:
%
%     P.layers(l)  - one mesh parameter set per layer, exactly the shape
%                    meshmodel.evaluate builds for a single mesh (theta, phi, sigma,
%                    outPhase, splits, lossDb, wavelength_m). That sameness is the
%                    point: err.phase_shifter_error, err.quantize,
%                    err.coupler_imbalance, err.mzi_loss, err.mesh_thermal_crosstalk
%                    and err.mesh_wavelength_dispersion apply to a layer unchanged.
%     P.eo         - one activation device per (mode, bank), nModes-by-(L-1):
%                    alpha, tia (ohm), resp (A/W), vPi, vBias (V) -- the raw device
%                    values the handoff carries -- plus dPhiB (rad, bias error),
%                    gainScale (calibration), s1/s2 (the activation MZI's coupler
%                    splits). Ideal: every device identical, errors zero, 50:50.
    nModes  = double(handoff.parameters.n_modes);
    nMzi    = double(handoff.parameters.n_mzi);
    nLayers = double(handoff.parameters.n_layers);
    hp = handoff.parameters;
    lambda0 = handoff.operating_point.wavelength_m;

    for l = nLayers:-1:1
        layers(l) = struct( ...
            'theta',    hp.phase_theta(:, l), ...
            'phi',      hp.phase_phi(:, l), ...
            'sigma',    hp.sigma(:, l), ...
            'outPhase', hp.out_phase(:, :, l).', ...     % 2-by-nModes, row m = mesh m
            'splits',   repmat(0.5, 2 * nMzi, 2), ...
            'lossDb',   zeros(2 * nMzi, 1), ...
            'wavelength_m', lambda0); %#ok<AGROW>
    end
    p.layers = layers;

    op = handoff.operating_point;
    sz = [nModes, nLayers - 1];
    p.eo = struct( ...
        'alpha',     repmat(op.eo_alpha, sz), ...
        'tia',       repmat(op.eo_tia_gain_ohm, sz), ...
        'resp',      repmat(op.eo_responsivity_a_per_w, sz), ...
        'vPi',       repmat(op.eo_v_pi, sz), ...
        'vBias',     repmat(op.eo_v_bias, sz), ...
        'dPhiB',     zeros(sz), ...
        'gainScale', ones(sz), ...
        's1',        repmat(0.5, sz), ...
        's2',        repmat(0.5, sz));
end
