"""Inline the free-space/chip correspondence widget for embedding.

Mirrors :mod:`apps.diffraction_explorer` and :mod:`apps.d2nn_demo`: this module
only bundles ``apps/web/analogy_geom.js`` (generated by
:mod:`apps.export_analogy_web`) and ``apps/web/analogy.js`` into inline
``<script>`` tags, so the explainer page stays CSP-safe and offline. The widget
draws pure geometry -- no weights, no propagation -- so the bundle is ~25 KB.

Run ``python -m apps.analogy_demo`` to write ``analogy_demo.html`` next to this
file, a standalone page carrying just the figure (handy for eyeballing it without
rebuilding the whole site).
"""
from __future__ import annotations

import json
import os

from apps import preview

from apps.diffraction_explorer import mount_script, read_web_asset


def analogy_bundle() -> str:
    """Return ``<script>`` tags with the geometry + widget inlined."""
    parts = [read_web_asset("analogy_geom.js"), read_web_asset("analogy.js")]
    return "\n".join(f"<script>\n{p}\n</script>" for p in parts)


def analogy_mount(container_id: str = "analogy", **opts) -> str:
    """Return a ``<script>`` that mounts the widget into ``#container_id``.

    ``opts`` are forwarded to ``PhotonnAnalogy.mount`` (currently just ``t``, the
    initial slider position in 0..1).
    """
    cfg = json.dumps(opts)
    return mount_script(container_id, f"window.PhotonnAnalogy.mount(el, {cfg});")


#: What this preview page says about the widget it is showing.
PREVIEW = dict(
    title="free space to chip",
    heading="Free space &rarr; chip",
    standfirst="A stack of phase masks in air and a mesh of interferometers on a chip are the\n"
               "  same alternating machine. They differ on one axis: how far a single layer reaches.",
    hosts=("analogy",),
)


def build_html(**opts) -> str:
    return preview.preview_page(bundle=analogy_bundle(), mount=analogy_mount(**opts),
                                **PREVIEW)


def save_demo(path: str = None, **opts) -> str:
    if path is None:
        path = preview.default_path(__file__, "analogy_demo")
    return preview.save_preview(path, build_html(**opts))


def main():
    path = save_demo()
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
