"""Inline the free-space/chip correspondence widget for embedding.

Mirrors :mod:`apps.diffraction_explorer` and :mod:`apps.d2nn_demo`: this module
only bundles ``apps/web/analogy_geom.js`` (generated by
:mod:`apps.export_analogy_web`) and ``apps/web/analogy.js`` into inline
``<script>`` tags, so the explainer page stays CSP-safe and offline. The widget
draws pure geometry -- no weights, no propagation -- so the bundle is ~25 KB.

Run ``python -m apps.analogy_demo`` to write ``analogy_demo.html`` next to this
file, a standalone page carrying just the figure (handy for eyeballing it without
rebuilding the whole site).
"""
from __future__ import annotations

import json
import os

from apps.diffraction_explorer import mount_script, read_web_asset


def analogy_bundle() -> str:
    """Return ``<script>`` tags with the geometry + widget inlined."""
    parts = [read_web_asset("analogy_geom.js"), read_web_asset("analogy.js")]
    return "\n".join(f"<script>\n{p}\n</script>" for p in parts)


def analogy_mount(container_id: str = "analogy", **opts) -> str:
    """Return a ``<script>`` that mounts the widget into ``#container_id``.

    ``opts`` are forwarded to ``PhotonnAnalogy.mount`` (currently just ``t``, the
    initial slider position in 0..1).
    """
    cfg = json.dumps(opts)
    return mount_script(container_id, f"window.PhotonnAnalogy.mount(el, {cfg});")


_PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>photonn &mdash; free space to chip</title>
<style>
  :root{{color-scheme:light dark;}}
  body{{margin:0;font:16px/1.5 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;
    background:#fff;color:#1b1f24;}}
  @media (prefers-color-scheme:dark){{body{{background:#0d1117;color:#e6eaf0;}}}}
  .wrap{{max-width:880px;margin:0 auto;padding:32px 22px 56px;}}
  h1{{font-size:1.5rem;margin:0 0 6px;}}
  .sub{{color:#5a6472;margin:0 0 22px;}}
  @media (prefers-color-scheme:dark){{.sub{{color:#9aa6b5;}}}}
</style>
</head>
<body>
<div class="wrap">
  <h1>Free space &rarr; chip</h1>
  <p class="sub">A stack of phase masks in air and a mesh of interferometers on a chip are the
  same alternating machine. They differ on one axis: how far a single layer reaches.</p>
  <div id="analogy"></div>
</div>
{bundle}
{mount}
</body>
</html>
"""


def build_html(**opts) -> str:
    return _PAGE.format(bundle=analogy_bundle(), mount=analogy_mount(**opts))


def save_demo(path: str = None, **opts) -> str:
    if path is None:
        path = os.path.join(os.path.dirname(__file__), "analogy_demo.html")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(build_html(**opts))
    return path


def main():
    path = save_demo()
    print(f"wrote {path} ({os.path.getsize(path) // 1024} KB)")


if __name__ == "__main__":
    main()
