"""Live in-browser D2NN classifier -- the Phase-2 deliverable, made tangible.

Builds a self-contained HTML page where the **trained** diffractive network runs
its forward pass in the browser: pick a frozen MNIST test digit or draw one, and
the digit is encoded into an entrance field, propagated through the five trained
phase masks, and classified by integrating intensity over ten detector regions.
Nothing is precomputed and nothing is fetched.

The pieces, all under ``apps/web``:

- ``asm.js``          -- the angular-spectrum engine (shared with the Phase-1 explorer)
- ``d2nn_weights.js`` -- the trained masks + geometry, generated by ``apps.export_d2nn_web``
- ``d2nn.js``         -- the network forward pass (port of ``photonn.models.D2NN``)
- ``d2nn_demo.js``    -- the widget

The JS is cross-checked against the torch model by ``tests/test_d2nn_crosscheck.py``
(identical predictions, logits within 1e-3). This module just inlines the bundle,
mirroring :mod:`apps.diffraction_explorer`; the same bundle is reused by
``apps.build_site`` for the explainer page.

Run ``python -m apps.d2nn_demo`` to write ``d2nn_demo.html`` next to this file.
"""
from __future__ import annotations

import json
import os

from apps.diffraction_explorer import read_web_asset


def d2nn_bundle(include_asm: bool = True) -> str:
    """Return ``<script>`` tags with the D2NN demo inlined (CSP-safe, offline).

    ``include_asm`` inlines the propagation engine too. Set it ``False`` on a page
    that already inlines ``asm.js`` (the explainer page does, for the Phase-1
    explorer) so the ~7 KB engine is not shipped twice.
    """
    parts = []
    if include_asm:
        parts.append(read_web_asset("asm.js"))
    parts.append(read_web_asset("d2nn_weights.js"))
    parts.append(read_web_asset("d2nn.js"))
    parts.append(read_web_asset("d2nn_demo.js"))
    parts.append(read_web_asset("d2nn_stage.js"))
    return "\n".join(f"<script>\n{p}\n</script>" for p in parts)


def d2nn_mount(container_id: str = "d2nn", stage_id: str = None, **opts) -> str:
    """Return a ``<script>`` that mounts the widget into ``#container_id``.

    ``opts`` are forwarded to ``PhotonnD2NN.mount`` (currently just ``gallery``,
    the index of the digit selected on load).

    With ``stage_id``, the 3D stage is mounted into that element and subscribed to
    the classifier, so both always show the same digit -- the page has exactly one
    digit source (the gallery and paint pad), never two out of sync.
    """
    cfg = json.dumps(opts)
    lines = [
        "<script>",
        "  window.addEventListener('DOMContentLoaded', function () {",
        f"    var demo = window.PhotonnD2NN.mount(document.getElementById('{container_id}'), {cfg});",
    ]
    if stage_id:
        lines += [
            f"    var stage = window.PhotonnD2NNStage.mount(document.getElementById('{stage_id}'));",
            "    demo.subscribe(function (res, meta) { stage.setResult(res, meta); });",
        ]
    lines += ["  });", "</script>"]
    return "\n".join(lines)


_PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>photonn &mdash; the optical classifier, live</title>
<style>
  :root{{color-scheme:light dark;}}
  body{{margin:0;font:16px/1.5 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;
    background:#fff;color:#1b1f24;}}
  @media (prefers-color-scheme:dark){{body{{background:#0d1117;color:#e6eaf0;}}}}
  .wrap{{max-width:880px;margin:0 auto;padding:32px 22px 56px;}}
  h1{{font-size:1.5rem;margin:0 0 6px;}}
  .sub{{color:#5a6472;margin:0 0 22px;}}
  @media (prefers-color-scheme:dark){{.sub{{color:#9aa6b5;}}}}
  .note{{margin-top:26px;font-size:13px;color:#5a6472;border-top:1px solid #d7dde5;padding-top:14px;}}
  @media (prefers-color-scheme:dark){{.note{{color:#9aa6b5;border-color:#30363d;}}}}
  code{{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.9em;}}
</style>
</head>
<body>
<div class="wrap">
  <h1>The optical classifier, live</h1>
  <p class="sub">A diffractive neural network trained in simulation, now running its forward
  pass in your browser. Light enters as a digit, diffracts through five phase masks, and
  lands on ten detectors. Nothing is precomputed and nothing is fetched.</p>
  <div id="stage"></div>
  <div id="d2nn"></div>
  <p class="note">The network reaches <strong>0.799</strong> on the MNIST test set, so roughly
  one digit in four is misread &mdash; the gallery includes examples it gets wrong. Hand-drawn
  digits are further out of distribution than MNIST test digits, so expect more errors there;
  that is a fair reading of the model, not a fault in the demo. The masks are the trained
  parameters exported from <code>photonn.models.D2NN</code>; the physics is the same
  angular-spectrum port used by the diffraction explorer, cross-checked against the PyTorch
  model to identical predictions and &lt;10<sup>&minus;3</sup> on the class scores.</p>
</div>
{bundle}
{mount}
</body>
</html>
"""


def build_html(**opts) -> str:
    """Return the full standalone demo HTML string."""
    opts.setdefault("stage_id", "stage")
    return _PAGE.format(bundle=d2nn_bundle(), mount=d2nn_mount(**opts))


def save_demo(path: str = None, **opts) -> str:
    """Write the standalone demo HTML and return its path."""
    if path is None:
        path = os.path.join(os.path.dirname(__file__), "d2nn_demo.html")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(build_html(**opts))
    return path


def main():
    path = save_demo()
    print(f"wrote {path} ({os.path.getsize(path) // 1024} KB)")


if __name__ == "__main__":
    main()
